AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  cloudprojectmaker

  Sample SAM Template for cloudprojectmaker
  
Metadata:
  AWS::ServerlessRepo::Application:
    Name: cloud-project-maker
    Description: >
      Lambda Function to grade the cloud project assignment.
    Author: Cyrus Wong
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['lambda','AWS_Educate']
    HomePageUrl: https://github.com/wongcyrus/managed-aws-educate-classroom
    SemanticVersion: 0.0.2
    SourceCodeUrl: https://github.com/wongcyrus/managed-aws-educate-classroom

Globals:
  Function:
    Timeout: 60

Resources:

  LibLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: lib/.
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: 'Available under the MIT-0 license.'
      RetentionPolicy: Delete     
      
  CloudProjectMarkerFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cloudprojectmarker/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - arn:aws:iam::aws:policy/job-function/ViewOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSQSReadOnlyAccess
      Layers:
        - !Ref LibLayer        

Outputs:
  CloudProjectMarkerFunction:
    Description: "CloudProjectMarkerFunction"
    Value: !GetAtt CloudProjectMarkerFunction.Arn